---
- name: My Test playbook
  hosts: all
  become: true
  tasks:

    - name: Copying file
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0600
        owner: Ajinkya
