---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:

    - name: Stopig the httpd
      service:
        name: httpd
        state: stopped

    - name: unistalling the httpd
      yum:
         name: httpd
         state: removed

